using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DialogueTrigger : MonoBehaviour
{
    [Header("Visual Cue")]
    [SerializeField] private GameObject visualCue;

    [Header("Ink JSON")]
    [SerializeField] private TextAsset inkJSON;

    private bool playerInRange;

    private void Awake()
    {
        playerInRange = false;
        visualCue.SetActive(false);
    }

    private void Update()
    {
        if (playerInRange && !DialogueManager.GetInstance().dialogueIsPlaying)
        {
            Debug.Log("Its Dialogue Time");
            //visualCue.SetActive(true);
            if (Input.GetKey(KeyCode.Space))
            {
                Debug.Log("SpaceBarPressed");
                DialogueManager.GetInstance().EnterDialogueMode(inkJSON);
            }
        }
        //else
        //{
        //    visualCue.SetActive(false);
        //}
    }

    private void OnTriggerEnter2D(Collider2D collider)
    {
        if (collider.gameObject.tag == "Player")
        {
            playerInRange = true;
            Debug.Log("Yeah, I'm thinking there was a collision");
        }
    }

    private void OnTriggerExit2D(Collider2D collider)
    {
        if (collider.gameObject.tag == "Player")
        {
            playerInRange = false;
        }
    }
}